### PR TITLE
[11.0][3830][UPD] website_sale_adj: change dependency

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[3830](https://www.quartile.co/web#id=3830&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

### CODE REVIEW

**Comment by kanda999** [comment]
@AungKoKoLin1997 
What do you think, moving the view adjustment to the `product_state` module would remove the dependency?

**Comment by AungKoKoLin1997** [comment]
> What do you think, moving the view adjustment to the `product_state` module would remove the dependency?

I don't think it is a good idea because product_state should be only for non website related module. So, Other modules just depend on this module for other purpose.

**Comment by kanda999** [comment]
> I don't think it is a good idea because product_state should be only for non website related module. So, Other modules just depend on this module for other purpose.

Got it. Please note that in the near future the website_sale_adj module will be split by purpose.

**Review by kanda999 — APPROVED** [review]

**Review by yostashiro — COMMENTED** [review]
@AungKoKoLin1997 Can you please add comments in the manifest file to indicate where the dependency comes from, in a similar manner as https://github.com/qrtl/axls-custom/blob/b370264/product_plm_import/__manifest__.py#L12-L13, unless it's obvious?

**Review by yostashiro — APPROVED** [review]

**Pull request merged**
