### PR TITLE
11.0 [2431][UPD] Update dot files

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
[2431](https://www.quartile.co/web#id=2431&action=771&model=project.task&view_type=form&menu_id=505)

### CODE REVIEW

**Review by yostashiro — CHANGES_REQUESTED** [review]
@AungKoKoLin1997 Please redo copier.

**Comment by AungKoKoLin1997** [comment]
@yostashiro I updated. But I am not sure how we should handle with pre-commit issues. There is the modules that are with wrong version format for license, author key, readme , others.

**Review by yostashiro — APPROVED** [review]
@AungKoKoLin1997 Thanks. Let's follow up on the pre-commit issues separately.

**Comment by yostashiro** [comment]
@AungKoKoLin1997 Can you please update https://github.com/qrtl/sst-custom/pull/316 with the latest template, and then @kanda999 should merge it.  Once that is done, please rebase your branch and run pre-commit, and discard all changes outside of this module.

**Comment by AungKoKoLin1997** [comment]
@kanda999 I already updated with latest template.

**Comment by kanda999** [comment]
@AungKoKoLin1997 I merged this.

**Pull request merged**
