### PR TITLE
st1 [1764][ADD] hr_attandance_rest_time

### PR DESCRIPTION
**Pull request by lehoangan**
[1764](https://www.quartile.co/web?debug=1#id=1764&action=771&model=project.task&view_type=form&menu_id=505)

### CODE REVIEW

**Comment by kakurai8** [comment]
Hi, @lehoangan 

Thank you very much for your quick response to my additional request.
The rest of the functions are perfect, but only the following parts do not seem to work as expected.
１．Rest Time (minutes) will also be auto-suggested for records created when the checkout button is pressed.
The classification is automatically set to work, the work location is automatically suggested, but the Rest Time is set to 0.
Please let me know if I missed anything on my end.

**Comment by kakurai8** [comment]
Hi, @lehoangan 

Have you already started working on the following project that I just asked you about?
If not, we will take care of it here.

> １．Rest Time (minutes) will also be auto-suggested for records created when the checkout button is pressed.
> The classification is automatically set to work, the work location is automatically suggested, but the Rest Time is set to 0.

I apologize for the change in schedule.
Thank you very much for your cooperation.

**Comment by lehoangan** [comment]
> Hi, @lehoangan
> 
> Have you already started working on the following project that I just asked you about?
> If not, we will take care of it here.
> 
> > １．Rest Time (minutes) will also be auto-suggested for records created when the checkout button is pressed.
> > The classification is automatically set to work, the work location is automatically suggested, but the Rest Time is set to 0.
> 
> I apologize for the change in schedule.
> Thank you very much for your cooperation.

Hi @kakurai8,

It means: I dont need to do it, right?

**Comment by yostashiro** [comment]
> It means: I dont need to do it, right?

@lehoangan That's right. I'm on it at the moment.

One question - any reason you added `working_hours` instead of using the standard `worked_hours` field by extending/overriding `_compute_worked_hours`?  I think we should stick to using the standard field this time.

**Comment by yostashiro** [comment]
@kakurai8 Please take care of the rest - update the translation and readme.

**Comment by lehoangan** [comment]
> > It means: I dont need to do it, right?
> 
> @lehoangan That's right. I'm on it at the moment.
> 
> One question - any reason you added `working_hours` instead of using the standard `worked_hours` field by extending/overriding `_compute_worked_hours`? I think we should stick to using the standard field this time.

Hi Yoshi,
There is a requirement:
>1-d. Add the checked lines to the output items when exporting from [Action].

The current field is a computed field. It is not shown as default fields in `Available fields` box on the export wizard. That's why I need to add one more normal file and add update data in create/write function

**Comment by kakurai8** [comment]
@yostashiro , @lehoangan 
I'm so sorry, this is my mistake.
Indeed, I had asked to add them to the output items.
>1-d. Add the checked lines to the output items when exporting from [Action].

However, it does not actually use the standard export.
When exporting, we use the web_export_view module to output the items displayed in the list screen.

**Comment by yostashiro** [comment]
> The current field is a computed field. It is not shown as default fields in `Available fields` box on the export wizard. That's why I need to add one more normal file and add update data in create/write function

@lehoangan You can export computed fields as well if you select 'Export all data', which doesn't go against the quoted requirement.  But please do let me know if you have any concerns over the changes I've made.

**Comment by lehoangan** [comment]
> > The current field is a computed field. It is not shown as default fields in `Available fields` box on the export wizard. That's why I need to add one more normal file and add update data in create/write function
> 
> @lehoangan You can export computed fields as well if you select 'Export all data', which doesn't go against the quoted requirement. But please do let me know if you have any concerns over the changes I've made.

Hi Youshi,
I have no problem with it. I just add it for a normal users.

**Comment by kakurai8** [comment]
st1 [1764][ADD] hr_attandance_rest_time #306
にマージしたためクローズ

**Pull request closed without merging**
