### PR TITLE
st1 [2331][ADD] tko_web_sessions_management

### PR DESCRIPTION
**Pull request by tack-yabeQuartile**
[2331](https://www.quartile.co/web#id=2331&action=771&model=project.task&view_type=form&menu_id=)

### CODE REVIEW

**Comment by yostashiro** [comment]
@tack-yabeQuartile Can we exclude the module from pre-commit.  It will keep breaking pre-commit forever, otherwise.

**Comment by tack-yabeQuartile** [comment]
pre-commit error .... a matter of cache?

```
pylint with optional checks..............................................Failed
- hook id: pylint
- duration: 0.58s
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/pylint/lint/run.py", line 254, in __init__
    linter.load_default_plugins()
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/pylint/lint/pylinter.py", line 483, in load_default_plugins
    checkers.initialize(self)
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/pylint/checkers/__init__.py", line 64, in initialize
    register_plugins(linter, __path__[0])
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/pylint/utils/utils.py", line 245, in register_plugins
    module = modutils.load_module_from_file(
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 240, in load_module_from_file
    return load_module_from_modpath(modpath)
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 225, in load_module_from_modpath
    return load_module_from_name(".".join(parts))
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/astroid/modutils.py", line 210, in load_module_from_name
    return importlib.import_module(dotted_name)
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/importlib/__init__.py", line [126](https://github.com/qrtl/sst-custom/runs/5674876846?check_suite_focus=true#step:4:126), in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/pylint/checkers/imports.py", line 49, in <module>
    import isort
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/isort/__init__.py", line 25, in <module>
    from . import settings  # noqa: F401
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/isort/settings.py", line 34, in <module>
    from .pie_slice import itemsview, lru_cache, native_str
  File "/home/runner/.cache/pre-commit/repoj_fgic72/py_env-python3/lib/python3.10/site-packages/isort/pie_slice.py", line 362, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
```

**Comment by tack-yabeQuartile** [comment]
In local env, **no error appears.**
 
But single warning appeared.
```
************* Module website_sale_adj.tests.test_website_sale_adj
website_sale_adj/tests/test_website_sale_adj.py:8: [W7950(odoo-addons-relative-import), ] Same Odoo module absolute import. You should use relative import with "." instead of "openerp.addons.website_sale_adj"
```

**Comment by yostashiro** [comment]
> pre-commit error .... a matter of cache?

@tack-yabeQuartile I think we need to apply the latest pre-commit config but I need to investigate.  I regard the PR to be good to go since you have run pre-commit locally.

**Review by yostashiro — APPROVED** [review]

**Pull request merged**
